import MainLayout from '@/components/admin/MainLayout'

export const metadata = {
  title: 'Aviator Admin',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <MainLayout>
      {children}
    </MainLayout>
  )
}
