
import MainLayout from '@/components/MainLayout'

export const metadata = {
  title: 'Aviator',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
   
      <div className='bg-[#090f1e] p-4'>
       <MainLayout>
          {children}
          </MainLayout>
      </div>
   
  )
}
